### PR TITLE
simplify layout, re #38

### PR DESCRIPTION
**Pull request by lazaridiscom**
Me not very familiar with the details of such low-level page design. Please feel free to change as you see fit, or to close without merge. 

(Sidenote: Changing the site content is too much effort. The site should be replaced by something simpler (e.g. generated out of a repository kept .md files). )

### CODE REVIEW

**Comment by SarahFowler73** [comment]
Thanks for taking a crack at this! I agree that the top content is WAY too big, but we don't want to get rid of the mailing list sign up, and don't want to completely remove the top content. I'm going to close this in favor of a slightly more nuanced approach, which will be a first step without thinking about an actual redesign. 

I'm curious what you mean about changing site content being too hard, and should be md. The content is actually md files already. You can find it in `/src/content`

**Comment by lazaridiscom** [comment]
> but we don't want to get rid of the mailing list sign up,

I did not remove it, I placed it within the footer, where it belongs.

> and don't want to completely remove the top content.

=> You insist to duplicate the footer in a redundant huge header. If you reduce the size of the header, it will look even stranger.

=> It is clear that someone at tezos has a "fetish" for huge headers, which makes fetching information from multiple sites highly inconvenient (as one must again and again scroll down when hopping around sites during a dive-in)

> I'm curious what you mean about changing site content being too hard, and should be md. The content is actually md files already. You can find it in /src/content

Sites should be designed in a way that non-techs can easily conceive/change them (e.g. without modules/imports etc.), ideally without the need to deal with PRs on messy github.

But it is very(!) clear that we have a different mentality.

So, all good!

**Comment by SarahFowler73** [comment]
Just to give some context, I don't own this repo; I just work on it, and can't make huge changes without approval. I made some "for now" updates to try to work with you, and address some of your concerns.

**Comment by lazaridiscom** [comment]
No worries, we're good. 

It is clearly a leadership incompetence/failure.

I'll not use tezos, see https://github.com/lazaridiscom/dapp-platform/issues/3

me out.

**Pull request closed without merging**
